# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Moovies' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'Firebase'
  pod 'RxSwift',    '~> 3.0.0-beta.1'
  pod 'RxCocoa',    '~> 3.0.0-beta.1'

  target 'MooviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
